version: '3'

# This is the default override for the development environment

services:

  ui:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
