version: '3'

networks:

  eyewitness_eyewitness-network:
    external: true

services:

  ui:
    environment:
      - TZ=Europe/London
    env_file:
      - .env
    volumes:
      - ./app:/src/app
      - ./lib:/src/lib
      - ./.env:/src/.env
      - ./webpack.config.js:/src/webpack.config.js
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
    networks:
      - eyewitness_eyewitness-network
    command: npm run start-development
    tty: true
    restart: on-failure
