version: '3'

networks:

  eyewitness_eyewitness-network:
    external: true

services:

  ui:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - NODE_ENV=development
      - TZ=Europe/London
      - PROVIDER_ID=
    volumes:
      - ./app:/src/app
      - ./.env:/src/.env
      - ./webpack.config.js:/src/webpack.config.js
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
    ports:
      - "5002:5002"
    networks:
      - eyewitness_eyewitness-network
    command: npm run start-development
    tty: true
    restart: on-failure
